package com.liuwei.mybatis.entity;

public class UserSexGenerator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sex.id
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_sex.sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sex.id
     *
     * @return the value of user_sex.id
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sex.id
     *
     * @param id the value for user_sex.id
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_sex.sex
     *
     * @return the value of user_sex.sex
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_sex.sex
     *
     * @param sex the value for user_sex.sex
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}