package com.liuwei.mybatis.dao;

import com.liuwei.mybatis.entity.UserSexGenerator;
import com.liuwei.mybatis.entity.UserSexGeneratorExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserSexGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    long countByExample(UserSexGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    int deleteByExample(UserSexGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    int insert(UserSexGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    int insertSelective(UserSexGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    List<UserSexGenerator> selectByExample(UserSexGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserSexGenerator record, @Param("example") UserSexGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sex
     *
     * @mbg.generated Wed Jul 01 22:51:23 CST 2020
     */
    int updateByExample(@Param("record") UserSexGenerator record, @Param("example") UserSexGeneratorExample example);
}